// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZP8FOyO9a8318HKfICyukk3TKcRYXAc',
    appId: '1:815425719795:web:2ff5ebe2b37de6c9655686',
    messagingSenderId: '815425719795',
    projectId: 'homework-ai-94113',
    authDomain: 'homework-ai-94113.firebaseapp.com',
    storageBucket: 'homework-ai-94113.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkwueQqDBGQ2eaKPDZoP2BLKV4rNq6w0Y',
    appId: '1:815425719795:android:2158968817cd1eeb655686',
    messagingSenderId: '815425719795',
    projectId: 'homework-ai-94113',
    storageBucket: 'homework-ai-94113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79xPI2h2iaqUYNIQ6ojliOXj6bwaZqAI',
    appId: '1:815425719795:ios:ffb0b61964a05874655686',
    messagingSenderId: '815425719795',
    projectId: 'homework-ai-94113',
    storageBucket: 'homework-ai-94113.firebasestorage.app',
    iosClientId: '815425719795-urt1lkolb70a7dubl8ae1dkqduettjge.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeworkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79xPI2h2iaqUYNIQ6ojliOXj6bwaZqAI',
    appId: '1:815425719795:ios:ffb0b61964a05874655686',
    messagingSenderId: '815425719795',
    projectId: 'homework-ai-94113',
    storageBucket: 'homework-ai-94113.firebasestorage.app',
    iosClientId: '815425719795-urt1lkolb70a7dubl8ae1dkqduettjge.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeworkAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQZP8FOyO9a8318HKfICyukk3TKcRYXAc',
    appId: '1:815425719795:web:2d91b04c69d35bd2655686',
    messagingSenderId: '815425719795',
    projectId: 'homework-ai-94113',
    authDomain: 'homework-ai-94113.firebaseapp.com',
    storageBucket: 'homework-ai-94113.firebasestorage.app',
  );
}
